version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  mysql:
    image: mysql:latest
    container_name: 'mysql'
    restart: always
    environment:
      MYSQL_DATABASE: 'dev'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"

  php_producer:
    build: ./Producer/.
    command: php index.php
    container_name: 'Producer'
    depends_on:
      - rabbitmq
    volumes:
      - './Producer:/var/www/html'
  
  php_consumer:
    build: ./Consumer/.
    command: php index.php
    container_name: 'Consumer'
    depends_on:
      - rabbitmq
      - mysql
    volumes:
      - './Consumer:/var/www/html'
    